
[theme]

base = "light"

primaryColor = "#7f8f88ff"

backgroundColor = "#9eb6b1ff"

secondaryBackgroundColor = "#a9c29eff"

textColor = "#ffffffff"

font = "sans serif"

[client]

showSidebarNavigation = true

[global]

dataFrameSerialization = "arrow"

[browser]
gatherUsageStats = false
